In [1]:
from sklearn import datasets
from layer import layer
import numpy as np

In [2]:

def sigmoid(z):
    return 1/(1+np.exp(-z))

In [31]:


# # generate random data
DATA, LABELS = datasets.make_classification(n_samples = 1000
                            ,n_features = 2
                            ,n_informative = 2
                            ,n_redundant = 0
                            ,n_clusters_per_class = 1
                            ,flip_y = 0
                            ,class_sep = 2
                            ,random_state = 7
                           )

LABELS = np.reshape(LABELS,newshape=(LABELS.shape[0],1))

M = DATA.shape[0]
N = DATA.shape[1]

In [32]:
l_0 = layer(input_size=2,units=3,activation="sigmoid")
l_1 = layer(input_size=3, units=1,activation="sigmoid")

In [33]:
DATA.shape

(1000, 2)

In [34]:
A_0 = l_0.forward(DATA)

In [35]:
A_0

array([[9.92383120e-01, 9.57326775e-01, 9.76736601e-01],
       [9.78120553e-01, 8.85182585e-01, 9.31668566e-01],
       [1.95965238e-01, 9.15079112e-02, 1.03071823e-01],
       ...,
       [9.88725083e-01, 9.26544860e-01, 9.59861271e-01],
       [9.89772054e-01, 9.44262091e-01, 9.68863452e-01],
       [1.83234027e-04, 5.11645142e-02, 1.21390144e-02]])

In [36]:
A_0.shape

(1000, 3)

In [37]:
A_1 = l_1.forward(A_0)

In [41]:
COST = -1 / M * np.sum(LABELS * np.log(A_1) + (1 - LABELS) * np.log(1 - A_1))

In [55]:
# derivative of cost function d(cost) / d(z_l) (i.e. the derivative up until the last layer before multiplying by the inputs)
# turn out to be : 1 / M * (output - LABELS) after that we can propogate back to the previous layer and so on
l_1_initial_derivative = 1 / M * (A_1 - LABELS)

In [56]:
l_1_wgrads = A_0.T @ l_1_initial_derivative

In [82]:
l_1_bgrads = np.sum(l_1_initial_derivative,axis= 0,)

In [66]:
# A_0 * ( 1 - A_0 ) is the derivative of the sigmoid function with respect to the input
l_0_initial_derivative = l_1_initial_derivative * l_1.weights.T * A_0 * ( 1 - A_0 )

In [76]:
l_0_initial_derivative.shape

(1000, 3)

In [71]:
l_0_wgrads  = DATA.T @ l_0_initial_derivative

In [86]:
l_0_bgrads = np.sum(l_0_initial_derivative , axis = 0)

In [87]:
l_0_bgrads

array([-0.00162351, -0.01348231,  0.00627324])

In [88]:
l_0_wgrads

array([[-0.00203204, -0.06696677,  0.02197419],
       [ 0.00507629,  0.06771886, -0.02782218]])